HH
SirKwest/hhclient pull request #16
Opened 2024-12-09 15:39 UTC by SirKwest

2024-12-10 18:44 UTC, AFxAster requested changes

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
> +    private val binding: ActivityRootBinding by lazy { ActivityRootBinding.inflate(layoutInflater) }
Точно не уверен, но ровно по тем же причинам почему во фрагментах нам стоит инитить биндинг в onCreateView и отвязывать его в onDestroyView, здесь стоит делать так же, только в onCreate и в onDestroy

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/java/ru/practicum/android/diploma/ui/favorites/FavoritesFragment.kt
> +        _binding = FragmentFavoritesBinding.inflate(inflater, container, false)
тогда сразу нужно отвязать его в onDestroyView

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/java/ru/practicum/android/diploma/ui/search/SearchFragment.kt
> +        _binding = FragmentSearchBinding.inflate(inflater, container, false)
то же самое, отвязать в onDestroyView

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/layout/activity_root.xml
> +        app:layout_constraintBottom_toTopOf="@id/main_navigation_view"
```suggestion
        app:layout_constraintBottom_toTopOf="@id/main_navigation_view_splitter"
```

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/layout/activity_root.xml
> +        android:id="@+id/main_navigation_view"
зачем нужна приставка main ко всем айди? Эти вью и так привязаны к макету мейна

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/layout/activity_root.xml
> +        android:id="@+id/mainFragmentContainerView"
```suggestion
        android:id="@+id/main_fragment_container_view"
```

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/menu/main_nav_menu.xml
> +        android:id="@id/searchFragment"
```suggestion
        android:id="@id/search_fragment"
```

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/menu/main_nav_menu.xml
> +        android:id="@id/favoritesFragment"
```suggestion
        android:id="@id/favorites_fragment"
```

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/menu/main_nav_menu.xml
> +        android:id="@id/teamFragment"
```suggestion
        android:id="@id/team_fragment"
```

2024-12-10 18:44 UTC, AFxAster commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_height="match_parent"
```suggestion
        android:layout_height="0dp"
```

2024-12-11 15:26 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
> +    private val binding: ActivityRootBinding by lazy { ActivityRootBinding.inflate(layoutInflater) }
у нас singleActivity - onDestroy на нем = смерть приложения, где все остатки подберет garbage collector.

Но дока Android согласна, поэтому - согласен, переделаем.

2024-12-11 15:30 UTC, SirKwest commented on app/src/main/res/layout/activity_root.xml
> +        android:id="@+id/main_navigation_view"
Имя не создать иллюзию другого объекта, позволяет однозначно идентифицировать объект, без опечаток. Можно было лучше? Возможно. Но тут точно нет проблемы, которую надо править.

2024-12-11 15:58 UTC, merged