HHC-11
SirKwest/hhclient pull request #17
Opened 2024-12-09 16:24 UTC by sandpaper-hub

2024-12-10 13:48 UTC, SirKwest requested changes

2024-12-10 13:48 UTC, SirKwest commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_19dp">19dp</dimen>
```suggestion
    <dimen name="dim_20dp">20dp</dimen>
```
Кажется, были многочисленные рекомендации по приведению всех размеров из макетов к кратным 4, поэтому

2024-12-10 13:48 UTC, SirKwest commented on app/src/main/res/layout/fragment_team.xml
> +    android:orientation="vertical">
А без этого верстка в бок пойдет? У нас в манифесте запрет на другую ориентацию.

2024-12-10 13:48 UTC, SirKwest commented on app/src/main/res/values/styles.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
```suggestion

```
Оно вроде как вылезло из тэга, да и вообще тут не нужно

2024-12-10 18:13 UTC, AFxAster commented on app/src/main/res/layout/fragment_team.xml
> +    android:orientation="vertical">
Ориентация приложения не играет никакой роли, а по умолчанию линеар лейаут ориентирован горизонтально

2024-12-10 18:17 UTC, AFxAster commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">wrap_content</item>
Я считаю что эти параметры лучше указывать каждую вью вручную, потому что стиль текста может один, а расположение и, соответственно, место текст занимает разное, не конкретно здесь а в целом. Плюс если будет неверное отображение, какие-то вью будут съедаться, будет сложно отслеживать причины, не видно что занимает каждая вью

2024-12-11 13:55 UTC, merged

2024-12-11 17:00 UTC, mdorogov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dim_19dp">19dp</dimen>
@SirKwest Ярослав, не встречал по программе про приведение размеров, у нас так всё поплывёт тогда