Hhc 57
SirKwest/hhclient pull request #65
Opened 2024-12-17 19:01 UTC by mdorogov

Сначала хотел сделать единый метод на поиск, но в итоге есть тперь отдельный, принимающий фильтры. Во фрагменте статичные данные и метод, по которому можно понимать, как это может работать в дальнейшем

2024-12-17 19:33 UTC, SirKwest commented
Ни в коем случае никакого отдельного метода на поиск, надо рефакторить оригинальный для приема новых параметров. 
Мой план был - передавать туда map из параметров запроса, а в интерфейсе ретрофита использовать [QueryMap](https://square.github.io/retrofit/2.x/retrofit/index.html?retrofit2/http/QueryMap.html)

2024-12-18 06:39 UTC, SirKwest requested changes
В дополнении ко всему остальному - когда задача стоит "подставляем значения фильтров в запрос на поиск" не надо добавлять ещё запросы на регионы, страны и прочие лишние изменения. Создается бОльшее пространство для ошибок и конфликтов с другими PR, кроме базового уровня не понимания "задача делает не то что она собиралась"

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/data/dto/VacancyShortDto.kt
> +    val area: RegionDto,
Это изменение ошибочно

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/data/impl/VacancyRepositoryImpl.kt
> +    override suspend fun searchVacanciesByOptions(page: Int, options: Map<String, String>): Flow<Resource> = flow {
В том числе и из-за необходимости писать дополнительный код для новых запросов, не надо делать новые запросы, вместо рефактора старых. Это потом невозможно поддерживать

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/data/network/HHApi.kt
> +    suspend fun getVacanciesByOptions(
Не надо такое добавлять, надо делать один запрос на этот endpoint

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/presentation/SearchFragmentViewModel.kt
> +    companion object {
компаньоны пишутся в конце объекта, как и было до изменений

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/ui/search/SearchFragment.kt
> +     */
Так как это было удалено в #21, видимо merge прошел не совсем правильно.

2024-12-18 06:39 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/ui/search/SearchFragment.kt
> +        queryMap.put("text", userText)
SearchFragment никогда не будет знать этих значений, отсюда они никогда приходить не будут

2024-12-18 20:48 UTC, mdorogov commented on app/src/main/java/ru/practicum/android/diploma/data/impl/VacancyRepositoryImpl.kt
> +    override suspend fun searchVacanciesByOptions(page: Int, options: Map<String, String>): Flow<Resource> = flow {
@SirKwest Да, понимаю. Непревычно переключиться на чисто одну задачу, не набрасывая ещё попутных параметров, без которых как кажется не будет работать основной метод.

2024-12-18 21:09 UTC, mdorogov commented on app/src/main/java/ru/practicum/android/diploma/presentation/SearchFragmentViewModel.kt
> +    companion object {
спасибо, убедился в доке, это так!

2024-12-19 08:42 UTC, mdorogov commented
@SirKwest Посмотри, пожалуйста

2024-12-19 12:09 UTC, SirKwest requested changes

2024-12-19 12:09 UTC, SirKwest commented on app/src/main/java/ru/practicum/android/diploma/presentation/SearchFragmentViewModel.kt
> +        val userTextRequestKey = "text"
Волшебная константа

2024-12-23 07:46 UTC, mdorogov commented
@SirKwest Ярослав, проверь изменения, пожалуйста

2024-12-25 11:02 UTC, closed without merging